window_set_cursor(cr_none);
border_left = 0;
border_right = room_width;
border_top = 0;
border_bottom = room_height;
fire_timer = 0;
fire_delay = 300;
player_hp=5;
flicker = false;
flicker_timer = 0;
flicker_interval = 10;
collision_enabled = true;
shield_cooldown=true;
sprite_index=spr_ship_Shield_ready;
depth=2;
	alarm[1]=60;
	collision_enabled=false;
	shield_cooldown=true;
	instance_create_layer(x,y,"Instances",O_shield);
	
	slowed=false;